name: Hprofile Actions

on: 
  workflow_dispatch:   # This allows the workflow to be manually triggered

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "Workflow works!"
