name: Hprofile Actions

on: 
  workflow_dispatch:   # This allows the workflow to be manually triggered

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Use 'uses' instead of 'run' for actions

      - name: Maven test
        run: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

